// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  artwork: dynamic(() => import("./Artwork")),
  hero: dynamic(() => import("./Hero")),
};
