// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  case_studies: dynamic(() => import("./CaseStudies")),
  gallery: dynamic(() => import("./Gallery")),
  hero: dynamic(() => import("./Hero")),
  intergrations: dynamic(() => import("./Integrations")),
  programming: dynamic(() => import("./Programming")),
  rich_text: dynamic(() => import("./RichText")),
};
